name: CI_lib
on: 
  push:
    branches: [ main , develop ]
  pull_request:
    branches: [ main , develop ]

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    
    steps:
      - name: Clone repo
        uses: actions/checkout@v4.2.0

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install SO dependencies
        run: sudo apt-get update && sudo apt-get install libgl1 -y

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install Poetry
        run: pip install poetry

      - name: Install cucaracha project dependecies
        run: poetry install

      - name: Run project tests
        run: poetry run task test --cov-report=xml --ignore-glob='./cucaracha/scripts/*.py'

      - name: Show-up test coverage (codecov)
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true

  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    
    steps:
      - name: Clone repo
        uses: actions/checkout@v4.2.0


      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install Poetry
        run: pip install poetry

      - name: Install cucaracha project dependecies
        run: poetry install

      - name: Run project tests
        run: poetry run task test --cov-report=xml --ignore-glob='./cucaracha/scripts/*.py'

      - name: Show-up test coverage (codecov)
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true

  mac:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    
    steps:
      - name: Clone repo
        uses: actions/checkout@v4.2.0


      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'  

      - name: Install Poetry
        run: pip install poetry

      - name: Install cucaracha project dependecies
        run: poetry install

      - name: Run project tests
        run: poetry run task test --cov-report=xml --ignore-glob='./cucaracha/scripts/*.py'

      - name: Show-up test coverage (codecov)
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
